name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app

    - name: Build and test
      run: xcodebuild clean build test -project iAddThree.xcodeproj -scheme iAddThreeCore -destination "platform=iOS Simulator,id=EA9AC207-6755-4AE9-ABCF-8E82595D54F6" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -quiet
